// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUp2p693RxtlXCOYvu5eDbZW5XfyffkO4',
    appId: '1:140549870532:web:a5a486e0bb783a3cb28a91',
    messagingSenderId: '140549870532',
    projectId: 'hasior-mess',
    authDomain: 'hasior-mess.firebaseapp.com',
    storageBucket: 'hasior-mess.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_b_JC-zVnlfwib0Wlafs6cnU4A_I4gwA',
    appId: '1:140549870532:android:e107f3828b0d488ab28a91',
    messagingSenderId: '140549870532',
    projectId: 'hasior-mess',
    storageBucket: 'hasior-mess.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxqqZSYTbR6WSIFCGpwtokzZQUdXpZyr4',
    appId: '1:140549870532:ios:578027dfad0a1ac8b28a91',
    messagingSenderId: '140549870532',
    projectId: 'hasior-mess',
    storageBucket: 'hasior-mess.appspot.com',
    iosBundleId: 'com.example.hasiorFlutter',
  );
}
